cleanup fnm and brew updates

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -338,13 +338,27 @@ __dko_dotfiles__update_node() {
 # ----------------------------------------------------------------------------
 
 __dko_dotfiles__node__update_fnm() {
-  if __dko_has brew; then
-    if __dko_has fnm; then
-      brew upgrade fnm
-    else
-      brew install fnm
-    fi
-  fi
+  [ -d "$FNM_DIR" ] || {
+    __dko_err "FNM_DIR not set, install dotfiles first"
+    return 1
+  }
+
+  case "$OSTYPE" in
+    linux*)
+      __dko_status "Re-run installer from https://github.com/Schniz/fnm"
+      ;;
+    *arwin*)
+      __dko_dotfiles__darwin__require_brew || return 1
+
+      if __dko_has brew; then
+        if __dko_has fnm; then
+          brew upgrade --verbose fnm
+        else
+          brew install --verbose fnm
+        fi
+      fi
+      ;;
+  esac
 }
 
 __dko_dotfiles__node__update_nvm() {
@@ -650,7 +664,8 @@ __dko_dotfiles__darwin__update_brew() {
     __dko_dotfiles__cd || exit 1
     __dko_dotfiles__pyenv_system
 
-    brew update
+    __dko_status "brew update"
+    brew update || exit 1
 
     # check if needed
     local outdated
@@ -661,14 +676,15 @@ __dko_dotfiles__darwin__update_brew() {
     }
 
     # Upgrade remaining
-    __dko_status "Upgrading packages"
-    brew upgrade
+    __dko_status "brew upgrade"
+    # We'll manually cleanup later
+    HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade --verbose || exit 1
     __dko_ok "Upgrade complete"
 
     __dko_dotfiles__darwin__update_brew_postupgrade "$outdated"
   ) && {
-    __dko_status "Clean up old versions and prune dead symlinks"
-    brew cleanup
+    __dko_status "brew cleanup - clean up old versions and prune dead symlinks"
+    brew cleanup --verbose
     __dko_ok "All clean"
   }
 }
@@ -706,7 +722,7 @@ __dko_dotfiles__darwin__update_brew_postupgrade() {
   # Detect if brew's python3 (not pyenv) was outdated
   if grep -q "python3" <<<"$outdated"; then
     __dko_status "Python3 was outdated, upgrading python3"
-    brew upgrade python3
+    brew upgrade --verbose python3
   fi
 
   __dko_ok "Post-upgrade complete"
