use printf

diff --git a/bin/eapache b/bin/eapache
--- a/bin/eapache
+++ b/bin/eapache
@@ -9,6 +9,6 @@ if apachectl -t >/dev/null 2>&1; then
     sudo -e "${apache_httpd_conf}"
   fi
 else
-  echo "Couldn't determine path to HTTPD conf file, check apachectl -t"
+  >&2 echo "Couldn't determine path to HTTPD conf file, check apachectl -t"
 fi
 
diff --git a/bin/git-in b/bin/git-in
--- a/bin/git-in
+++ b/bin/git-in
@@ -19,14 +19,12 @@ __check_in_repository() {
 # exit with message if invalid usage
 __check_args() {
   if (( $# == 0 )); then
-    echo "ERROR: Please provide a path argument."
-    echo
+    >&2 echo "ERROR: Please provide a path argument."
     exit 1
   fi
 
   if [ ! -f "$1" ] && [ ! -d "$1" ]; then
-    echo "ERROR: Path does not exist."
-    echo
+    >&2 echo "ERROR: Path does not exist."
     exit 1
   fi
 }
@@ -44,19 +42,19 @@ __git_in() {
 
   dir_path="$(realpath "$dir_path")"
   cd -- "$dir_path" || {
-    echo "ERROR: Could not enter $dir_path"
+    >&2 printf 'ERROR: Could not enter %s\ns' "$dir_path"
     exit 1
   }
 
   if __check_in_repository; then
-    echo "local repo    $(git rev-parse --show-toplevel)"
+    printf 'local repo    %s\n' "$(git rev-parse --show-toplevel)"
 
     remote="$(git config --get remote.origin.url)"
     if [ -n "$remote" ]; then
-      echo "with origin   $remote"
+      printf 'with origin   %s\n' "$remote"
     fi
   else
-    echo "Path is not in a repo."
+    >&2 echo "ERROR: Path is not in a repo."
     exit 1
   fi
 }
diff --git a/bin/rln b/bin/rln
--- a/bin/rln
+++ b/bin/rln
@@ -33,15 +33,15 @@ _rln() {
   local new_source
   new_source="${original_dir}/${newname_for_source}"
 
-  echo "old source: $original_source"
-  echo "new source: $new_source"
+  printf 'old source: %s\n' "$original_source"
+  printf 'new source: %s\n' "$new_source"
 
   if [[ "$(basename "$original_source")" == "$(basename "$new_source")" ]]; then
-    echo "WARNING: new source \"${new_source}\""
-    echo "         and original source \"${original_source}\""
-    echo "         already have the same name. Skipping."
+    printf 'WARNING: new source "%s"\n' "$new_source"
+    printf '         and original source "%s"\n' "$original_source"
+    printf '         already have the same name. Skipping.\n'
   elif [ -e "$new_source" ]; then
-    echo "WARNING: new source \"${new_source}\" exists. Please remove it first. Skipping."
+    printf 'WARNING: new source "%s" exists. Please remove it first. Skipping.\n' "$new_source"
   else
     mv "$original_source" "$new_source" \
     && ln -sf "$new_source" "$target_file" \
@@ -53,7 +53,7 @@ _rln() {
 if [ -z "$1" ] || [ -z "$2" ]; then
   _usage;
 elif ! test -L "$1"; then
-  echo "ERROR: Invalid target_file $1"
+  >&2 printf 'ERROR: Invalid target_file %s\n' "$1"
   exit 1
 else
   _rln "$1" "$2"
