0 is okay

diff --git a/bin/togglemousescaling b/bin/togglemousescaling
--- a/bin/togglemousescaling
+++ b/bin/togglemousescaling
@@ -7,10 +7,10 @@ __togglemousescaling() {
   local desired
 
   if (( $# > 0 )); then
-    if [[ $1 =~ ^[1-3]$ ]]; then
+    if [[ $1 =~ ^[0-3]$ ]]; then
       desired="$1"
     else
-      >&2 echo "Invalid value, expected 1, 2 or 3."
+      >&2 echo "Invalid value, expected 0, 1, 2 or 3."
       return 1
     fi
   else
