egr and egrunt fns

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -83,6 +83,35 @@ dog() {
   fi
 }
 
+# find and edit Gruntfile in project
+#
+egrunt() {
+  egr "Gruntfile.js" >/dev/null 2>&1 || \
+  egr "Gruntfile.coffee" >/dev/null 2>&1 || \
+  {>&2 echo "Gruntfile not found" && return 1}
+}
+
+# find and edit file from git root
+#
+egr() {
+  local filename="${1:-README.md}"
+  local git_root="./"
+
+  # check for git root
+  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    git_root="$(git rev-parse --show-toplevel)"
+  fi
+
+  # edit gruntfile in git root or local dir if exists
+  if [ -f "${git_root}/${filename}" ]; then
+    vopen "${git_root}/${filename}"
+  else
+    >&2 echo "No file to edit."
+    return 1
+  fi
+}
+
+
 # PHP version numbers
 # @TODO use cut instead of splitting awk?
 phpver() {
